#!/bin/sh
#
# Note: this is a sample and will not be run as is.  Change the name of this
# file to <gdmconfdir>/PostLogin/Default for this script to be run.  This
# script will be run before any setup is run on behalf of the user and is
# useful if you for example need to do some setup to create a home directory
# for the user or something like that.  $HOME, $LOGIN and such will all be
# set appropriately and this script is run as root.

if [ "${LOGNAME}" = "estudante" ]; then
    rm -rf "${HOME}"
    cd /home
    tar zxf /var/lib/laboaideia/home/home-estudante.tgz
fi

data_hora="$(date +%F_%T)"
env >> "/tmp/post-login_${data_hora}_$$.sh"

exit 0

